project:
  type: website

website:
  title: "My first Quarto website"
  navbar:
    left:
      - text: "R Series"
        menu: 
         - text: "Episode 9"
           href: Episode9.html
      - text: "Now Your See It!"
        href: introTableau.html
      - text: "Introduction to QGIS"
        href: introQGIS.html
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

